---
title: "Basic_example"
author: "Brian J. Knaus"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Basic_example}
  %\VignetteEncoding{UTF-8}
  %\VignetteEngine{knitr::rmarkdown}
bibliography: GAPIT3doc.bib
editor_options: 
  chunk_output_type: console
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```


```{r setup, include=FALSE}
library(GAPIT3documentation)
knitr::opts_chunk$set(fig.align = "center")
```



## A basic example


```{r, eval=TRUE}
t1 <- Sys.time()

# system.file("extdata", "mdp_traits.txt.gz", package = "GAPIT3documentation")
# system.file("extdata", "mdp_genotype_test.hmp.txt.gz", package = "GAPIT3documentation")

#Step 1: Set data directory and import files
# myY <- read.table("mdp_traits.txt", head = TRUE)
# myG <- read.table("mdp_genotype_test.hmp.txt", head = FALSE)

myPhenoFile <- system.file("extdata", "mdp_traits.txt.gz",
                    package = "GAPIT3documentation")
myGenoFile <- system.file("extdata", "mdp_genotype_test.hmp.txt.gz",
                    package = "GAPIT3documentation")

myPhenotypes <- read.table(myPhenoFile, header = TRUE)
myGenotypes  <- read.table(myGenoFile, header = FALSE)

head(myPhenotypes)
myGenotypes[1:4, 1:9]
```



```{r, eval=TRUE}
#Step 2: Run GAPIT
library(GAPIT3)
#myGAPIT <- GAPIT3documentation::GAPIT(
#
myGAPIT <- GAPIT(
#  Y=myPhenotypes,
  Y=myPhenotypes[, 1:2],
  G=myGenotypes,
  PCA.total=3
)
```


## Return object


```{r}
class(myGAPIT)
names(myGAPIT)
lapply(myGAPIT, class)
```


## Outfiles


```{r}
getwd()
list.files(path = ".", pattern = "^GAPIT.")
```



```{r}
t99 <- Sys.time()
t99 - t1
```


